---
- hosts: reinservr
  vars:
    resinurl: http://caucho.com/download/resin-4.0.64.tar.gz
    downloaddir : /usr/local/share
    resinarhive:  "{{downloaddir}}/resin-4.0.64.tar.gz"
    resindir: "{{downloaddir}}/resin-4.0.64"

  tasks:
    - name: Install necessary packages
      yum:
          state: present
          name:
            - gcc
            - make

    - name: Download resin
      get_url: url="{{resinurl}}" dest="{{downloaddir}}"

    - name: Unpack archive
      command: "tar -zxf {{resinarhive}} -C {{downloaddir}} creates={{resindir}}"

    - name: Running ./configure for FFMPEG
      shell: "{{ item }}"
      args:
        chdir: "{{ resindir }}"
      with_items:
        - ./configure --enable-64bit --enable-ssl

    - name: Build the default target
      make:
        chdir: "{{resindir}}"

    - name: Run 'install' target as root
      make:
        chdir: "{{resindir}}"
        target: install
      become: yes

    - name: Start resin service
      service:
        enabled: yes
        name: resin
        state: started
